# site settings
url: "http://letsta.lk"
baseurl: ""
# "http://abrelatam.org"
twitter_username: go_letstalk
analytics: 'UA-61272908-1'

# build settings
markdown: kramdown

en:
  title: Let's Talk 
  description: "Chat with companies for free."
es:
  title: Let's Talk 
  description: "Chatea gratis con empresas y servicios."
